version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME:-school_transport}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      DB_ENGINE: postgres
      DB_NAME: ${DB_NAME:-school_transport}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379/1
      SECRET_KEY: change-me
      DEBUG: "True"
volumes:
  pgdata:
