name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pip install black isort ruff
          black --check .
          isort --check-only .
          ruff check .
      - name: Django checks
        env:
          SECRET_KEY: dummy
          DEBUG: "True"
        run: |
          python manage.py check
      - name: Migrate (SQLite for CI)
        env:
          SECRET_KEY: dummy
          DEBUG: "True"
        run: |
          python manage.py migrate --noinput
